name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        set -e

        # Install Node.js and PM2 if not present
        if ! command -v node &> /dev/null; then
          curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
          sudo yum install -y nodejs
        fi

        if ! command -v pm2 &> /dev/null; then
          sudo npm install -g pm2
        fi

        # Create app directory if it doesn't exist
        mkdir -p ~/my-app
        cd ~/my-app

        # Clone or pull latest changes
        if [ ! -d .git ]; then
          git clone https://github.com/iskilicaslan61/Roman-Numerals-Converter.git .
        else
          git pull
        fi

        npm install
        pm2 restart app || pm2 start app.js --name app
        EOF
