name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ec2-user
        APP_DIR: /home/ec2-user/Roman-Numerals-Converter
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          APP_DIR=/home/ec2-user/Roman-Numerals-Converter

          # Python and Git setup
          sudo yum install -y python3 git

          # Clone or update the repository
          if [ ! -d "$APP_DIR" ]; then
            git clone https://github.com/iskilicaslan61/Roman-Numerals-Converter.git $APP_DIR
          else
            sudo chown -R ec2-user:ec2-user $APP_DIR
            cd $APP_DIR
            git config --global --add safe.directory "$APP_DIR"
            git pull origin main
          fi

          cd $APP_DIR

          # Create a virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate

          # Upgrade pip and install dependencies
          pip install --upgrade pip
          pip install flask

          # Ensure the app is not already running
          pkill -f roman-numerals-converter-app.py || true

          # Start the Flask app in the background  
          nohup python3 roman-numerals-converter-app.py > app.log 2>&1 &

        EOF
