name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2 and run Flask app
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          # Project directory
          APP_DIR=~/Roman-Numerals-Converter

          # Install dependencies
          sudo yum install -y python3 git

          # Clone repo or pull latest changes
          if [ ! -d "$APP_DIR" ]; then
            git clone https://github.com/ismailkilicaslan/Roman-Numerals-Converter.git $APP_DIR
          else
            cd $APP_DIR
            git pull origin main
          fi

          cd $APP_DIR

          # Create systemd service
          sudo tee /etc/systemd/system/romanapp.service > /dev/null <<EOL
          [Unit]
          Description=Flask Roman Numerals App
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=$APP_DIR
          ExecStart=/usr/bin/python3 $APP_DIR/roman-numerals-converter-app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOL

          # Start the service
          sudo systemctl daemon-reexec
          sudo systemctl daemon-reload
          sudo systemctl enable romanapp
          sudo systemctl restart romanapp
        EOF
