name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ec2-user
        APP_DIR: /home/ec2-user/Roman-Numerals-Converter
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          APP_DIR=/home/ec2-user/Roman-Numerals-Converter

          # Python 3 ve Git kurulu mu kontrol et
          sudo yum install -y python3 git

          # Proje dizini varsa izinleri düzelt, yoksa klonla
          if [ ! -d "$APP_DIR" ]; then
            git clone https://github.com/iskilicaslan61/Roman-Numerals-Converter.git $APP_DIR
          else
            sudo chown -R ec2-user:ec2-user $APP_DIR
            cd $APP_DIR
            git config --global --add safe.directory "$APP_DIR"
            git pull origin main
          fi

          cd $APP_DIR

          # Sanal ortam oluştur ve aktif et
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate

          # Gerekli python paketlerini yükle
          pip install --upgrade pip
          pip install -r requirements.txt

          # Uygulamayı pm2 ile başlat (pm2 yoksa yükle)
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          pm2 describe roman-numerals-converter || pm2 start roman-numerals-converter-app.py --interpreter python3 --name roman-numerals-converter
          pm2 save
          pm2 restart roman-numerals-converter

          
        EOF
