name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH and verify connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -v ${{ secrets.EC2_HOST }} "echo '✅ SSH connected successfully!'"

    - name: Deploy and restart Flask app
      run: |
        ssh ${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/Roman-Numerals-Converter
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          pkill -f app.py || true
          nohup python app.py > output.log 2>&1 &
        EOF
